##############
### prd
##############
server:
  port: 9080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 5s
    max-connections: 1000
    accept-count: 20
    threads:
      max: 200

spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.43.12.210:40001/admin
    username: admin
    #password: caravan
    password: admin

# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
    loggers:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,prometheus,loggers,metrics,caches,beans
#        include: "*"

springdoc:
  show-actuator: true  # actuator swagger 노출
  swagger-ui:
    groups-order: DESC
    #operations-sorter: alpha
    #tags-sorter: alpha
    disable-swagger-default-url: true
    #doc-expansion: none

#logging:
#  level:
#    com.kt.edu: trace
#    org.springframework.security: DEBUG
#    org:
#      keycloak:
#        admin:
#          client: DEBUG
